import mapper from '../mapper'

export default mapper([
  '36:Kicks|Kick',
  '37:Snares|Snare Rimshot L',
  '38:Snares|Snare Open Hit L',
  '39:Snares|Snare Rimshot R',
  '40:Snares|Snare Open Hit R',
  '41:Snares|Snare Shallow Rimshot',
  '42:Snares|Snare Sidestick',
  '43:Snares|Snare Shallow Hit',
  '44:Snares|Snare Rim Click',
  '45:Rides|Ride Pearl',
  '46:Cymbals|Cymbal 1',
  '47:Perc|Cowbell',
  '48:Hats|HH Pedal Closed',
  '49:Hats|HH Closed1 Pearl',
  '50:Hats|HH Closed1 Shaft',
  '51:Hats|HH Closed2 Pearl',
  '52:Hats|HH Closed2 Shaft',
  '53:Hats|HH Closed Bell',
  '54:Hats|HH Open A',
  '55:Hats|HH Open B',
  '56:Hats|HH Open C',
  '57:Hats|HH Open D',
  '58:Hats|HH Open Bell',
  '59:Hats|HH Pedal Open',
  '60:Rides|Ride Pearl',
  '61:Rides|Ride Bell',
  '62:Rides|Ride Shaft',
  '63:Rides|Ride Choke',
  '65:Toms|Tom 4 Open Hit',
  '66:Toms|Tom 4 Rimshot',
  '67:Toms|Tom 3 Open Hit',
  '68:Toms|Tom 3 Rimshot',
  '69:Toms|Tom 2 Open Hit',
  '70:Toms|Tom 2 Rimshot',
  '71:Toms|Tom 2 Open Hit',
  '72:Toms|Tom 2 Rimshot',
  '75:Other|Sticks',
  '77:Cymbals|Cymbal 1',
  '78:Cymbals|Cymbal 1 Choke',
  '79:Cymbals|Cymbal 2',
  '80:Cymbals|Cymbal 2 Choke',
  '81:Cymbals|Cymbal 3',
  '82:Cymbals|Cymbal 3 Choke',
])
