import mapper from '../mapper'

export default mapper([
  '27:Perc|MS-20 Squeak',
  '28:Perc|White Noise',
  '29:Perc|Scratch',
  '30:Perc|Scratch',
  '31:Snares|Rim Shot',
  '32:Perc|TR-55 Clave',
  '33:Kicks|SK-1 Kick',
  '34:Perc|Chime',
  '35:Kicks|Ludwig Kick',
  '36:Kicks|Ludwig Kick',
  '37:Snares|Ludwig Rim',
  '38:Snares|Ludwig Snare',
  '39:Snares|Ludwig Ruff',
  '40:Snares|Tight Snare',
  '41:Toms|Tom',
  '42:Hats|HH Closed',
  '43:Toms|Tom 2',
  '44:Hats|HH Pedal',
  '45:Toms|Tom 3',
  '46:Hats|HH Open',
  '47:Toms|Tom 4',
  '48:Toms|Roto Tom',
  '49:Cymbals|Crash',
  '50:Toms|Roto Tom',
  '51:Rides|Ping Ride',
  '52:Cymbals|China',
  '53:Rides|Ping Ride Bell',
  '54:Perc|Tamborine',
  '55:Cymbals|Splash',
  '56:Perc|Cowbell',
  '57:Cymbals|Crash 2',
  '58:Perc|Vibra slap',
  '59:Rides|Ping Ride',
  '60:Perc|Bongo Hi',
  '61:Perc|Bongo Open',
  '62:Perc|Conga',
  '63:Perc|Conga Tone',
  '64:Perc|Conga Open',
  '65:Perc|Timbale Hi',
  '66:Perc|Timbale Lo',
  '67:Perc|Agogo Hi',
  '68:Perc|Agogo Lo',
  '69:Perc|Cabasa',
  '70:Perc|Shaker',
  '71:Perc|Whistle Short',
  '72:Perc|Whistle Long',
  '73:Perc|Guiro Short',
  '74:Perc|Guiro Long',
  '75:Perc|909 Clave',
  '76:Perc|Wood Block Hi',
  '77:Perc|Wood Block Lo',
  '78:Perc|Quica',
  '79:Perc|Quica',
  '80:Perc|Triangle Mute',
  '81:Perc|Triangle Open',
  '82:Perc|Shaker',
  '83:Perc|Jingle Bell',
  '84:Perc|Bell Tree down',
  '85:Perc|Rim/Clap',
  '86:Perc|Soprano Drum',
  '87:Perc|Soprano Drum',
  '89:Perc|Tabla',
  '90:Perc|Tabla',
  '93:Perc|909 Clave',
  '94:Perc|Block Hi',
  '95:Perc|Block Lo',
  '98:Perc|Triangle Mute',
  '99:Perc|Triangle Open',
  '100:Perc|Shaker',
  '101:Perc|Ambient Rasp Hi',
  '102:Perc|Ambient Rasp Lo',
  '103:Perc|Tick',
  '104:Perc|Soprano Drum',
  '105:Perc|Soprano Drum',
])
