import mapper from '../mapper'

export default mapper([
  '27:Perc|MS-20 Squeak',
  '28:Perc|MS-20 Rim',
  '29:Perc|Scratch It',
  '30:Perc|Scratch Stop',
  '31:Snares|Side Stick Dist',
  '32:Perc|TR-55 Clave',
  '33:Kicks|SK-1 Kick',
  '34:Kicks|SK-1 Kick',
  '35:Kicks|Gretsch Kick',
  '36:Kicks|Gretsch Kick 2',
  '37:Snares|Side Stick',
  '38:Snares|Lugwig Snare',
  '39:Snares|Buzz Roll',
  '40:Snares|Wood Snare',
  '41:Toms|Gretsch Tom',
  '42:Hats|HH Closed',
  '43:Toms|Gretsch Tom 2',
  '44:Hats|HH Pedal',
  '45:Toms|Roto Tom',
  '46:Hats|HH Open',
  '47:Toms|Roto Tom 2',
  '48:Toms|Roto Tom 2',
  '49:Cymbals|Paiste Crash',
  '50:Toms|Roto Tom 2',
  '51:Rides|Ride',
  '52:Cymbals|China',
  '53:Rides|Ride 2',
  '54:Perc|Nanjira',
  '55:Cymbals|Splash',
  '56:Perc|Cowbell',
  '57:Cymbals|Crash remix',
  '58:Perc|Vibraslap',
  '59:Cymbals|Paiste Crash 2',
  '60:Perc|Bongo Hi',
  '61:Perc|Bongo Lo',
  '62:Perc|Conga Open',
  '63:Perc|Conga Slap',
  '64:Perc|Tumba Slap',
  '65:Perc|Dumbek',
  '66:Perc|Small Dumbek',
  '67:Perc|Agogo',
  '68:Perc|Agogo',
  '69:Perc|Shakerine',
  '70:Perc|Shaker',
  '71:Perc|Whistle',
  '72:Perc|Whistle Hi',
  '73:Perc|Guiro Chif',
  '74:Perc|Guiro Scratch',
  '75:Perc|Clap',
  '76:Perc|Temple Block Ho',
  '77:Perc|Temple Block Lo',
  '78:Perc|Metal Cup Lo',
  '79:Perc|Metal Cup Hi',
  '80:Perc|Rebar Hit',
  '81:Perc|Rebar Open',
])
