import mapper from '../mapper'

export default mapper([
  '21:Hats|HH Pedal',
  '22:Hats|HH Closed Edge',
  '23:Hats|HH Pedal Splash',
  '24:Hats|HH Open 1',
  '25:Hats|HH Open 2',
  '26:Hats|HH Open 3',
  '27:Cymbals|Crash A (alias)',
  '28:Cymbals|Crash A (alias)',
  '29:Cymbals|Crash A (sustained)',
  '30:Cymbals|Crash B (alias)',
  '31:Cymbals|Crash B (alias)',
  '32:Cymbals|Crash B (sustained)',
  '33:Snares|Snare Left',
  '34:Kicks|Kick (alias)',
  '35:Kicks|Kick (alias)',
  '36:Kicks|Kick Right',
  '37:Snares|Sidestick',
  '38:Snares|Snare Right',
  '39:Snares|Snare Right',
  '40:Snares|Rimshot',
  '41:Toms|Floor Tom (alias)',
  '42:Hats|HH Closed',
  '43:Toms|Floor Tom',
  '44:Hats|HH Pedal',
  '45:Toms|Rack Tom 2 (alias)',
  '46:Hats|HH Open',
  '47:Toms|Rack Tom 2',
  '48:Toms|Rack Tom 1 (alias)',
  '49:Cymbals|Crash A',
  '50:Toms|Rack Tom 1',
  '51:Rides|Ride Bow',
  '52:Cymbals|Crash B',
  '53:Rides|Ride Bell',
  '54:Cymbals|Crash A Muted',
  '55:Cymbals|Crash A Sustained',
  '56:Perc|Cowbell',
  '57:Cymbals|Crash B Sustained',
  '58:Cymbals|Crash B Muted',
  '59:Rides|Ride Edge',
  '60:Hats|HH Open Max',
  '61:Hats|HH Closed Tip',
  '62:Hats|HH Tight',
  '63:Hats|HH Tight Tip',
  '64:Hats|HH Seq Hard',
  '65:Hats|HH Seq Soft',
])
