import mapper from '../mapper'

export default mapper([
  '23:Other|IMAP - GM Switch',
  '24:Other|Preset Change UP',
  '25:Snares|Sidestick Alt',
  '26:Other|Preset Change DOWN',
  '27:Snares|Rimshot Alt',
  '28:Toms|Hi Tom Alt',
  '29:Toms|Hi Tom Edge Alt',
  '30:Toms|Tom 1 Rimshot Alt',
  '31:Toms|Mid Tom Alt',
  '32:Toms|Tom 2 Rimshot Alt',
  '33:Toms|Mid Tom Edge Alt',
  '34:Toms|Tom 3 Rimshot Alt',
  '35:Toms|Low Tom Alt',
  '36:Toms|Low Tom Edge Alt',
  '37:Hats|Hi Hat Open Alt',
  '38:Snares|Snare Center Alt',
  '39:Hats|Hi Hat Bell',
  '40:Snares|Snare Edge Alt',
  '41:Hats|Hi Hat Foot Open',
  '42:Snares|Snare Roll Alt',
  '43:Kicks|Kick Soft Alt',
  '44:Snares|Snare Roll',
  '45:Kicks|Kick Soft',
  '46:Snares|Snare Ghost Note',
  '47:Kicks|Kick Hard Alt',
  '48:Kicks|Kick Hard',
  '49:Snares|Snare Sidestick/Other',
  '50:Snares|Snare Center',
  '51:Snares|Snare Rimshot/Other',
  '52:Snares|Snare Edge',
  '53:Hats|Hi Hat Foot Shut',
  '54:Hats|Hi Hat Closed Inside',
  '55:Hats|Hi Hat Closed Alt',
  '56:Hats|Hi Hat Edge',
  '57:Hats|Hi Hat Choke',
  '58:Hats|Hi Hat Open',
  '59:Hats|Hi Hat Open (Bonham)',
  '60:Cymbals|Crash 1 Edge',
  '61:Cymbals|Crash 1 Inside',
  '62:Rides|Ride Edge',
  '63:Rides|Ride Bell',
  '64:Toms|Hi Tom Alt',
  '65:Toms|Hi Tom',
  '66:Toms|Hi Tom Edge',
  '67:Toms|Mid Tom Alt',
  '68:Toms|Mid Tom Edge',
  '69:Toms|Mid Tom',
  '70:Toms|Low Tom Edge',
  '71:Toms|Low Tom Alt',
  '72:Toms|Low Tom',
  '73:Cymbals|Crash Bell',
  '74:Rides|Ride Edge Alt',
  '75:Rides|Ride Bell Alt',
  '76:Rides|Ride Crash',
  '77:Cymbals|Crash Choke',
  '78:Cymbals|Crash 2 Choke',
  '79:Cymbals|Crash 2 Edge',
  '80:Cymbals|Crash 2 Inside',
  '81:Cymbals|Crash 2 Roll',
  '82:Cymbals|Crash 2 Bell',
  '83:Cymbals|Crash 2 Roll Alt',
  '84:Cymbals|Splash 1 Outside',
  '85:Cymbals|Splash 1 Inside',
  '86:Cymbals|China 1 Outside',
  '87:Cymbals|China 1 Inside',
  '88:Cymbals|China 1 Choke',
  '89:Cymbals|Splash 1 Choke',
])
