import mapper from '../mapper'

export default mapper([
  '27:Perc|Snaps',
  '28:Perc|Noise 1',
  '29:Perc|Cuica Mute',
  '30:Perc|Cuica Mute',
  '31:Perc|Half Stick',
  '32:Perc|Claves',
  '33:Perc|Metal Stick',
  '34:Perc|Triangle Open',
  '35:Kicks|Kick Rim',
  '36:Kicks|Kick',
  '37:Snares|Side Stick',
  '38:Snares|Snare',
  '39:Perc|TR808 Clap 1',
  '40:Snares|Snare Rim',
  '41:Toms|Tom 3',
  '42:Hats|HH Closed',
  '43:Toms|Tom 3 Rim',
  '44:Hats|HH Pedal',
  '45:Toms|Tom 2',
  '46:Hats|HH Open',
  '47:Toms|Tom 2 Rim',
  '48:Toms|Tom 1',
  '49:Cymbals|Crash',
  '50:Toms|Tom 1 Rim',
  '51:Rides|Ride',
  '52:Cymbals|Crash Edge',
  '53:Rides|Ride Edge',
  '54:Perc|Tambourine 1',
  '55:Cymbals|Splash',
  '56:Perc|Cowbell',
  '57:Cymbals|Crash 2',
  '58:Perc|Vibra Slap',
  '59:Rides|Brush Ride',
  '60:Perc|Bongo High',
  '61:Perc|Bongo Low',
  '62:Perc|Conga High Mute',
  '63:Perc|Conga High Open',
  '64:Perc|Comgo Low Open',
  '65:Perc|Timbale High',
  '66:Perc|Timbale Low',
  '67:Perc|Agogo 1',
  '68:Perc|Agogo 2',
  '69:Perc|Cabasa',
  '70:Perc|Maracas',
  '71:Perc|Whistle Short',
  '72:Perc|Whistle Long',
  '73:Perc|Guiro Short',
  '74:Perc|Guiro Long',
  '75:Perc|Claves',
  '76:Perc|Wood Block 1',
  '77:Perc|Wood Block 2',
  '78:Perc|Cuica Mute',
  '79:Perc|Cuica Open',
  '80:Perc|Triangle Mute',
  '81:Perc|Triangle Open',
  '82:Perc|Shaker',
  '83:Perc|Tambourine 1',
  '84:Perc|Random 2',
  '85:Perc|Half Stick',
  '86:Perc|Taiko',
  '87:Perc|Taiko',
])
