import mapper from '../mapper'

export default mapper([
  '27:Perc|High Q',
  '28:Perc|Slap',
  '29:Perc|Scratch Push',
  '30:Perc|Scratch Pull',
  '31:Perc|Stick',
  '32:Perc|Square Click',
  '33:Perc|Metronome Click',
  '34:Perc|Metronome Bell',
  '35:Kicks|Standard Bass Drum 2',
  '36:Kicks|Classic Bass Drum 1',
  '37:Snares|Side Stick',
  '38:Snares|Classic Snare 1',
  '39:Snares|Hand Clap',
  '40:Snares|Classic Rim Shot',
  '41:Toms|Classic Tom 6',
  '42:Hats|Classic Close Hi-Hat',
  '43:Toms|Classic Tom 5',
  '44:Hats|Classic Hi-Hat Foot',
  '45:Toms|Classic Tom 4',
  '46:Hats|Classic Open Hi-Hat',
  '47:Toms|Classic Tom 3',
  '48:Toms|Classic Tom 2',
  '49:Cymbals|Classic Crash 1',
  '50:Toms|Classic Tom 1',
  '51:Rides|Classic Ride1',
  '52:Cymbals|Classic China',
  '53:Rides|Classic Ride Bell',
  '54:Perc|Tambourine',
  '55:Cymbals|Classic Splash',
  '56:Perc|Cowbell',
  '57:Cymbals|Classic Crash 2',
  '58:Perc|Vibra Slap',
  '59:Rides|Classic Ride 2',
  '60:Perc|Hi Bongo',
  '61:Perc|Low Bongo',
  '62:Perc|Mute Conga',
  '63:Perc|Hi Conga',
  '64:Perc|Low Conga',
  '65:Perc|High Timbale',
  '66:Perc|Low Timbale',
  '67:Perc|High Agogo',
  '68:Perc|Low Agogo',
  '69:Perc|Cabasa',
  '70:Perc|Maracas',
  '71:Perc|Short Whistle',
  '72:Perc|Long Whistle',
  '73:Perc|Short Guiro',
  '74:Perc|Long Guiro',
  '75:Perc|Claves',
  '76:Perc|Hi Wood Block',
  '77:Perc|Low Wood Block',
  '78:Perc|Mute Cuica',
  '79:Perc|Open Cuica',
  '80:Perc|Mute Triangle',
  '81:Perc|Open Triangle',
  '82:Perc|Shaker',
  '83:Perc|SleighBell',
  '84:Perc|Belltree',
  '85:Perc|Castanets',
  '86:Perc|Mute Surdo',
  '87:Perc|Open Surdo',
  '88:Perc|Taiko',
  '89:Perc|LotusDrum',
  '90:Perc|Rain Stick',
  '91:Perc|Finger Snaps',
  '92:Perc|Finger Cymbals',
  '93:Perc|Finger Cymbals Muted',
  '94:Perc|Bell Tree',
  '95:Perc|Gong',
  '96:Perc|Spring',
])
