import mapper from '../mapper'

export default mapper([
  '27:Perc|High Q',
  '28:Perc|Slap',
  '29:Perc|Scratch Push',
  '30:Perc|Scratch Pull',
  '31:Perc|Sticks',
  '32:Perc|Square Click',
  '33:Perc|Metronome Click',
  '34:Perc|Metronome Bell',
  '35:Kicks|Acoustic Bass Drum ',
  '36:Kicks|Bass Drum 1',
  '37:Snares|Side Stick',
  '38:Snares|Acoustic Snare',
  '39:Snares|Hand Clap',
  '40:Snares|Hard Snare Drum',
  '41:Toms|Low Floor Tom',
  '42:Hats|Closed Hi-Hat',
  '43:Toms|High Floor Tom',
  '44:Hats|Pedal Hi-Hat',
  '45:Toms|Low Tom',
  '46:Hats|Open Hi-Hat',
  '47:Toms|Low-Mid Tom',
  '48:Toms|Hi-Mid Tom',
  '49:Cymbals|Crash Cymbal 1',
  '50:Toms|High Tom',
  '51:Rides|Ride Cymbal 1',
  '52:Cymbals|Chinese Cymbal',
  '53:Rides|Ride Bell',
  '54:Perc|Tambourine',
  '55:Cymbals|Splash Cymbal',
  '56:Perc|Cowbell',
  '57:Cymbals|Crash Cymbal 2',
  '58:Perc|Vibraslap',
  '59:Rides|Ride Cymbal 2',
  '60:Perc|Hi Bongo',
  '61:Perc|Low Bongo',
  '62:Perc|Mute Hi Conga',
  '63:Perc|Open Hi Conga',
  '64:Perc|Low Conga',
  '65:Perc|High Timbale',
  '66:Perc|Low Timbale',
  '67:Perc|High Agogo',
  '68:Perc|Low Agogo',
  '69:Perc|Cabasa',
  '70:Perc|Maracas',
  '71:Perc|Short Whistle',
  '72:Perc|Long Whistle',
  '73:Perc|Short Guiro',
  '74:Perc|Long Guiro',
  '75:Perc|Claves',
  '76:Perc|Hi Wood Block',
  '77:Perc|Low Wood Block',
  '78:Perc|Mute Cuica',
  '79:Perc|Open Cuica',
  '80:Perc|Mute Triangle',
  '81:Perc|Open Triangle',
  '82:Perc|Shaker',
  '83:Perc|Jingle Bell',
  '84:Perc|Belltree',
  '85:Perc|Castanets',
  '86:Perc|Mute Surdo',
  '87:Perc|Open Surdo',
])
